easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          # if administrators are allowed to edit users' passwords and roles, add this:
