<?php

namespace App\Controller\Admin;

use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
Use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
Use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;


use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;

class UserCrudController extends AbstractCrudController

{
   public const roles= '';
 public const role = array('ROLE_QUE_TU_VEUX');


    public static function getEntityFqcn(): string
    {
        return User::class;

    }
/*public function new(AdminContext $context)
{
   // return parent::new($context); // TODO: Change the autogenerated stub
    $context->roles = array('ROLE_SUPER_ADMIN ');
}*/




    public function configureFields(string $pageName): iterable
     {

         return [
             TextField::new('email'),
             TextField::new('username'),
             //TextField::new('firstName'),
             TextField::new('plainPassword')->onlyOnForms(),
             TextField::new('email'),
             TextField::new('role')->hideOnIndex()->hideOnForm()->setCustomOption(self::roles,'ROLE_ADMIN";}'),
             BooleanField::new('enabled'),


         ];
     }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            // the labels used to refer to this entity in titles, buttons, etc.
            ->setEntityLabelInSingular('User')
            ->setEntityLabelInPlural('Users')

            // the Symfony Security permission needed to manage the entity
            // (none by default, so you can manage all instances of the entity)
            ->setEntityPermission('ROLE_SUPER_ADMIN')

            ;
    }
}
